App_Login/urls.py
from django.urls import path
from .import views
app_name = "App_Login"


urlpatterns = [
    path('signup/',views.sign_up,name = 'sign_up'),
    path('login/',views.Login_page,name = "login"),
    path('edit/',views.edit_profile,name = "edit"),
    path('logout/',views.logout_user,name = "logout"),
    path('profile/',views.profile,name = "profile"),
    path('user/<username>',views.user,name = "user"),
    path('follow/<username>/',views.follow,name = "follow"),
    path('unfollow/<username>/',views.unfollow,name = "unfollow"),
    
]

App_Post/urls.py
from django.urls import path
from .import views
app_name = "App_Post"


urlpatterns = [
 path('',views.home,name = "home"),
 path('liked/<pk>/',views.liked,name = "liked"),
 path('unliked/<pk>/',views.unliked,name = "unliked"),
    
]

My_Social_Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from App_Post import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('App_Login.urls')),
    path('post/',include('App_Post.urls')),
    path('',views.home,name = "home"),
  
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <title>{% block title %}Social{% endblock %}</title>
    {% block css_block %}
    {% endblock %}
</head>
<body>
    <div class="container" style="padding-top:20px">
      {% block content %}
      {% endblock %}


    </div>
    
</body>
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
   <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %}Social{% endblock %}</title>
    {% block css_block %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class = "navbar-nav">
            <li class = "nav-item active">
                <a href="{% url 'App_Post:home' %}" class = "nav-link"><img src="/media/Logo.png" alt=""></a>



            </li>
            
           
            
            &nbsp;&nbsp;&nbsp;&nbsp;
            <form class="form-inline" method = "GET">
               
                  <input type="text" class="form-control mr-sm-2" name = "search" placeholder="Search">
               
                  <button type="submit" class="btn btn-success">Search</button>
                 
            </form>
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            

            <li class = "nav-item">
                <br>
               
               
                <a href="{% url 'App_Login:logout' %}" class = "nav-link">Log Out</a>



            </li>



             <li class = "nav-item">
                {% if user.user_profile.profile_pic %}
                <br>
                
                <a href="{% url 'App_Login:profile' %}" class = "nav-link"><img src="/media/{{ user.user_profile.profile_pic }}" alt="" width="40px" height = "40px" class = "rounded-circle"></a>

                {% else %}
                <br>
                
                <a href="{% url 'App_Login:profile' %}" class = "nav-link"><img src="/media/avatar.jpg" alt="" width="40px" height = "40px" class = "rounded-circle"></a>

                {% endif %}

            



            </li>





        </ul>



    </nav>


    <div class="container" style="padding-top:20px">
      {% block content %}
      {% endblock %}


    </div>
    
</body>
  
</html>